# https://taskfile.dev

version: '3'

shopt: [globstar]

vars:
  INFRA_DIR: infra
  TAG_NAME: "us-west1-docker.pkg.dev/r13-knifeworks/r13knifeworks-docker-repo/r13knifeworks-website:r13knifeworks"

tasks:
  docker-build:
    cmds:
      - docker image rm --force r13knifeworks
      - cd server && docker buildx build --platform=linux/amd64 --tag "{{.TAG_NAME}}" .

  deploy:
    cmds:
      - docker push "{{.TAG_NAME}}"
